### ISSUE TITLE
i got a error how to fix it?

### ISSUE THREAD

**Issue by chong1227** [friday/lottie-node#9]
```
undefined:6284
        elementWidth = this.canvasContext.canvas.width * this.renderConfig.dpr;
                                          ^

TypeError: Cannot read property 'canvas' of null
    at CanvasRenderer.updateContainerSize (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:6284:43)
    at CanvasRenderer.configAnimation (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:6272:10)
    at AnimationItem.configAnimation (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:11417:19)
    at AnimationItem.setParams (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:11284:14)
    at Object.loadAnimation (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:11068:18)
    at Object.loadAnimation (eval at <anonymous> (C:\Users\Snow\lottie\node_modules\lottie-node\index.js:42:3), <anonymous>:14282:33)
    at C:\Users\Snow\lottie\node_modules\lottie-node\index.js:52:24
    at Object.<anonymous> (C:\Users\Snow\lottie\examples\render-png.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

```

**Comment by chong1227** [comment]
i fixed it
